// ------------------------------------------------------------
// Thunder Buster
// ------------------------------------------------------------
class NSHThunderBuster:ThunderBuster{// Replaces ThunderBuster{
	override void DrawHUDStuff(HDStatusBar sb,HDWeapon hdw,HDPlayerPawn hpl){
		if(sb.hudlevel==1){
			sb.drawbattery(-54,-4,sb.DI_SCREEN_CENTER_BOTTOM,reloadorder:true);
			sb.drawnum(hpl.countinv("HDBattery"),-46,-8,sb.DI_SCREEN_CENTER_BOTTOM);
		}
		if(hdw.weaponstatus[0]&TBF_ALT){
			sb.drawimage(
				"STBURAUT",(-28,-10),
				sb.DI_SCREEN_CENTER_BOTTOM|sb.DI_TRANSLATABLE|sb.DI_ITEM_RIGHT
			);
			sb.drawnum(int(2000/HDCONST_ONEMETRE),-16,-17,sb.DI_SCREEN_CENTER_BOTTOM,font.CR_GRAY);
		}else sb.drawnum(hdw.weaponstatus[TBS_MAXRANGEDISPLAY],-16,-17,sb.DI_SCREEN_CENTER_BOTTOM,font.CR_GRAY);
		int bat=hdw.weaponstatus[TBS_BATTERY];
		if(bat>0)sb.drawwepnum(bat,20);
		else if(!bat)sb.drawstring(
			sb.mamountfont,"00000",
			(-16,-9),sb.DI_TEXT_ALIGN_RIGHT|sb.DI_TRANSLATABLE|sb.DI_SCREEN_CENTER_BOTTOM,
			Font.CR_DARKGRAY
		);
		if(hdw.weaponstatus[TBF_SAFETY])sb.drawimage("SAFETY",(-17,-16),sb.DI_SCREEN_CENTER_BOTTOM,scale:(1,1));	
	}
	
	override string gethelptext()
	{
		if(!Cvar.GetCVar("mrnsha_binds", Owner.Player).GetBool())LocalizeHelp();
		else
		{
			MRHD_WeapAnimsHandler Handler = MRHD_WeapAnimsHandler(EventHandler.Find("MRHD_WeapAnimsHandler"));
			
			if(Handler)Handler.MRHD_GetWeaponKeyBinds(Self);
		}
		
		return
		LWPHELP_FIRESHOOT
		..LWPHELP_ALTFIRE..StringTable.Localize("$THBWH_SWITCH")..(weaponstatus[0]&TBF_ALT?StringTable.Localize("$THBWH_DETONATOR"):StringTable.Localize("$THBWH_SCATTERSHOT"))..StringTable.Localize("$THBWH_MODE")
		..LWPHELP_RELOADRELOAD
		..LWPHELP_UNLOADUNLOAD
		..LWPHELP_ALTRELOAD..StringTable.Localize("$THBWH_ALTRELOAD").."\n"
		..LWPHELP_USE.."+"..LWPHELP_FIREMODE..StringTable.Localize("$LWPHELP_SAFETY")
		..LWPHELP_ZOOM.."+"..LWPHELP_RELOAD..StringTable.Localize("$LWPHELP_CHECKCHARGE")
		;
	}
	override void DrawSightPicture(
		HDStatusBar sb,HDWeapon hdw,HDPlayerPawn hpl,
		bool sightbob,vector2 bob,double fov,bool scopeview,actor hpc
	){
		int Light = Owner.CurSector.LightLevel*1.75;
		if(owner.player.fixedlightlevel==1)Light = 255;
		int cx,cy,cw,ch;
		[cx,cy,cw,ch]=screen.GetClipRect();
		sb.SetClipRect(
			-16+bob.x,-4+bob.y,32,16,
			sb.DI_SCREEN_CENTER
		);
		vector2 bobb=bob*1.2;
		sb.drawimage(
			"tbfrntsit",(0,0)+bobb,sb.DI_SCREEN_CENTER|sb.DI_ITEM_TOP
		);
		if(CVar.GetCVar("mrnsha_sights", owner.player).GetBool())
		sb.drawimage(
			"TBBLFTSIT",(0,0)+bobb,sb.DI_SCREEN_CENTER|sb.DI_ITEM_TOP, Col:Color(254-Light, 0,0,0)
		);
		sb.SetClipRect(cx,cy,cw,ch);
		sb.drawimage(
			"tbbaksit",(0,0)+bob,sb.DI_SCREEN_CENTER|sb.DI_ITEM_TOP,
			alpha:0.9
		);
		if(CVar.GetCVar("mrnsha_sights", owner.player).GetBool())
		sb.drawimage(
			"TBBLKSIT",(0,0)+bob,sb.DI_SCREEN_CENTER|sb.DI_ITEM_TOP,
			alpha:0.9, Col:Color(254-Light, 0,0,0)
		);
		
		if(scopeview){
			bool alt=hdw.weaponstatus[0]&TBF_ALT;
			int scaledyoffset=36;

			name ctex="HDXCAM_TB";

			texman.setcameratotexture(hpc,ctex,3);
			sb.drawimage(
				ctex,(0,scaledyoffset)+bob,sb.DI_SCREEN_CENTER|sb.DI_ITEM_CENTER,
				alpha:alt?(hpl.flip?0.7:0.8):1.,scale:((0.25/1.2),0.25)
			);
			let tb=ThunderBuster(hdw);
			sb.drawnum(min(tb.rangefinder,999),
				24+bob.x,12+bob.y,sb.DI_SCREEN_CENTER,
				(
					tb.rangefinder>=10
					&&tb.rangefinder<hdw.weaponstatus[TBS_MAXRANGEDISPLAY]
				)?Font.CR_GRAY:Font.CR_RED
				,0.4
			);
			sb.drawnum(hdw.weaponstatus[TBS_MAXRANGEDISPLAY],
				24+bob.x,20+bob.y,sb.DI_SCREEN_CENTER,Font.CR_WHITE,0.4
			);
			if(alt)sb.drawnum(int(2000/HDCONST_ONEMETRE),
				23+bob.x,19+bob.y,sb.DI_SCREEN_CENTER,Font.CR_BLACK,1.
			);
			sb.drawimage(
				"tbwindow",(0,scaledyoffset)+bob,sb.DI_SCREEN_CENTER|sb.DI_ITEM_CENTER,
				scale:(1,1)
			);
			if(CVar.GetCVar("mrnsha_sights", owner.player).GetBool())
			sb.drawimage(
				"tbBlk",(0,scaledyoffset)+bob,sb.DI_SCREEN_CENTER|sb.DI_ITEM_CENTER,
				scale:(1,1), col:Color(254-Light, 0,0,0)
			);
			bobb*=3;
			double dotoff=max(abs(bobb.x),abs(bobb.y));
			if(dotoff<40)sb.drawimage(
				"redpxl",(0,scaledyoffset)+bobb,sb.DI_SCREEN_CENTER|sb.DI_ITEM_TOP,
				alpha:(alt?0.4:0.9)*(1.-dotoff*0.04),scale:alt?(hpl.flip?(3,3):(1,1)):(2,2)
			);
		}
	}
	static void ThunderZap(
		actor caller,
		double zoffset=32,
		bool alt=false,
		int battery=20
	){
		//determine angle
		double shootangle=caller.angle;
		double shootpitch=caller.pitch;
		vector3 shootpos=(0,0,zoffset);
		let hdp=hdplayerpawn(caller);
		if(hdp){
			shootangle=hdp.gunangle;
			shootpitch=hdp.gunpitch;
			shootpos=hdp.gunpos;
		}
		if(alt){
			shootangle+=frandom(-1.2,1.2);
			shootpitch+=frandom(-1.3,1.1);
		}

		//create the line
		flinetracedata tlt;
		caller.linetrace(
			shootangle,
			8000+200*battery,
			shootpitch,
			flags:TRF_NOSKY|TRF_ABSOFFSET,
			offsetz:shootpos.z,
			offsetforward:shootpos.x,
			offsetside:shootpos.y,
			data:tlt
		);


		if(
			tlt.hittype==Trace_HitNone
			||(
				tlt.hitline&&(
					tlt.hitline.special==Line_Horizon
					||(
						tlt.linepart==2
						&&tlt.hitsector.gettexture(0)==skyflatnum
					)||(
						tlt.linepart==1
						&&tlt.hitline.sidedef[1]
						&&hdmath.oppositesector(tlt.hitline,tlt.hitsector).gettexture(0)==skyflatnum
					)
				)
			)
		)return;

		//alt does a totally different thing
		if(alt){
			if(tlt.hittype==Trace_HitNone||tlt.distance>2000)return;
			actor bbb=spawn("BeamSpotFlash",tlt.hitlocation-tlt.hitdir,ALLOW_REPLACE);
			bbb.setz(clamp(bbb.pos.z,bbb.floorz,bbb.ceilingz-8));
			if(!random(0,3))(lingeringthunder.zap(bbb,bbb,caller,40,true));
			beamspotflash(bbb).impactdistance=tlt.distance-16*battery;
			bbb.angle=caller.angle;
			bbb.A_SprayDecal("Scorch",12);
			bbb.pitch=caller.pitch;
			bbb.target=caller;
			bbb.tracer=tlt.hitactor; //damage inflicted on the puff's end
			if(tlt.hitline)doordestroyer.CheckDirtyWindowBreak(tlt.hitline,0.005*battery,tlt.hitlocation);
			return;
		}

		int basedmg=int(max(0,20-tlt.distance*(1./50.)));
		int dmgflags=caller&&caller.player?DMG_PLAYERATTACK:0; //don't know why the player damagemobj doesn't work

		if(tlt.hitline)doordestroyer.CheckDirtyWindowBreak(tlt.hitline,0.003*basedmg,tlt.hitlocation);

		//wet actor
		if(
			tlt.hitactor
		){
			actor hitactor=tlt.hitactor;
			if(hitactor.bloodtype=="ShieldNotBlood"){
				hitactor.damagemobj(null,caller,random(1,(battery<<2)),"Balefire",dmgflags);
			}else if(
				hitactor.bnodamage
				||hitactor.bnoblood
				||hitactor.bloodtype=="NotQuiteBloodSplat"
				||random(0,7)
				||hitactor.countinv("ImmunityToFire")
				||HDWoundFixer.CheckCovered(hitactor,true)
			){
				//dry actor - ping damage and continue
				if(!random(0,5))(lingeringthunder.zap(hitactor,hitactor,caller,40,true));
				hdf.give(hitactor,"Heat",(basedmg>>1));
				hitactor.damagemobj(null,caller,1,"electrical",dmgflags);
			}else{
				//wet actor
				if(!random(0,7))(lingeringthunder.zap(hitactor,hitactor,caller,(basedmg<<1),true));
				hdf.give(hitactor,"Heat",(basedmg<<1));
				hitactor.damagemobj(null,caller,basedmg,"electrical",dmgflags);
				actor sss=spawn("HDGunsmoke",tlt.hitlocation,ALLOW_REPLACE);
				sss.vel=(0,0,1)-tlt.hitdir;
				return;
			}
		}
		//where where the magic happens happens
		actor bbb=spawn("BeamSpot",tlt.hitlocation-tlt.hitdir,ALLOW_REPLACE);
		bbb.setz(clamp(bbb.pos.z,bbb.floorz,bbb.ceilingz-8));
		bbb.target=caller;
		bbb.stamina=basedmg;
		bbb.angle=caller.angle;
		bbb.pitch=caller.pitch;
	}
	action void A_ThunderZap(){
		if(invoker.weaponstatus[TBS_HEAT]>20)return;
		int battery=invoker.weaponstatus[TBS_BATTERY];
		if(battery<1){
			setweaponstate("nope");
			return;
		}

		//preliminary effects
		A_ZoomRecoil(0.99);
		A_StartSound("weapons/plasidle");
		if(IsMoving.Count(self)>9)A_MuzzleClimb(frandom(-0.8,0.8),frandom(-0.8,0.8));

		//the actual call
		ThunderBuster.ThunderZap(
			self,
			gunheight(),
			invoker.weaponstatus[0]&TBF_ALT,
			battery
		);

		//aftereffects
		if(invoker.weaponstatus[0]&TBF_ALT){
			if(!random(0,4))invoker.weaponstatus[TBS_BATTERY]--;
			A_MuzzleClimb(
				frandom(0.05,0.2),frandom(-0.2,-0.4),
				frandom(0.1,0.3),frandom(-0.2,-0.6),
				frandom(0.04,0.12),frandom(-0.1,-0.3),
				frandom(0.01,0.03),frandom(-0.1,-0.2)
			);
			invoker.weaponstatus[TBS_HEAT]+=6;
		}else if(!random(0,6))invoker.weaponstatus[TBS_BATTERY]--;
		invoker.weaponstatus[TBS_HEAT]+=random(0,3);

		//update range thingy
		invoker.weaponstatus[TBS_MAXRANGEDISPLAY]=int(
			(battery>0?battery*200+8000:0)/HDCONST_ONEMETRE
		);
	}
	states{
	Safety:
		---- A 0 {A_StartSound("weapons/fmswitch",CHAN_WEAPON,CHANF_OVERLAP,0.4);
			invoker.weaponstatus[TBF_SAFETY]=!invoker.weaponstatus[TBF_SAFETY];}
		Goto Nope;
	ready:
		---- A 0 A_JumpIf(pressinguse()&&pressingfiremode(),"Safety");
		PLSG A 1{
			A_CheckIdSprite("THBGA0","PLSGA0");
			invoker.weaponstatus[TBS_WARMUP]=0;

			//update rangefinder
			if(
				invoker.weaponstatus[TBS_BATTERY]>0
				&&!(level.time&(1|2|4))
				&&max(abs(vel.x),abs(vel.y),abs(vel.z))<2
				&&(
					!player.cmd.pitch
					&&!player.cmd.yaw
				)
			){
				vector3 gunpos=gunpos();
				flinetracedata frt;
				linetrace(
					angle,
					512*HDCONST_ONEMETRE,
					pitch,
					flags:TRF_NOSKY|TRF_ABSOFFSET,
					offsetz:gunpos.z,
					offsetforward:gunpos.x,
					offsetside:gunpos.y,
					data:frt
				);
				if(
					frt.hittype==Trace_HitNone
					||(
						frt.hittype==Trace_HitCeiling
						&&frt.hitsector.gettexture(1)==skyflatnum
					)||(
						frt.hittype==Trace_HitFloor
						&&frt.hitsector.gettexture(0)==skyflatnum
					)||(
						!!frt.hitline
						&&frt.hitline.special==Line_Horizon
					)
				)invoker.rangefinder=999;
				else invoker.rangefinder=int(frt.distance*(1./HDCONST_ONEMETRE));
			}
			A_WeaponReady(WRF_ALL&~WRF_ALLOWUSER1);
		}
		#### # 0 A_OverlayFlags(PSP_WEAPON, PSPF_INTERPOLATE, 1);
		goto readyend;
		
		
		PLSG AB 0;
		PLSF AB 0;
		THBG AB 0;
		THBF AB 0;
		
	fire:
		---- A 0 A_JumpIf(invoker.weaponstatus[TBF_SAFETY]==1,"Nope");
		#### A 3 offset(0,35);
	hold:
		#### A 0 A_JumpIf(invoker.weaponstatus[TBS_BATTERY]>0,"shoot");
		goto nope;
	shoot:
		#### A 1 offset(1,33) A_ThunderZap();
		#### A 1 offset(0,34) A_WeaponReady(WRF_NONE);
		#### A 1 offset(-1,33) A_WeaponReady(WRF_NONE);
		#### A 0{
			if(invoker.weaponstatus[TBS_BATTERY]<1){
				A_StartSound("weapons/plasmas",CHAN_WEAPON);
				A_GunFlash();
				setweaponstate("nope");
			}else{
				A_Overlay(PSP_FLASH+1, "RecoilLay");
				A_Refire();
			}
		}
		#### AAA 4{
			A_WeaponReady(WRF_NOFIRE);
			A_GunFlash();
		}goto ready;
	flash:
		THBF AB 0;
		#### A 0 A_CheckIdSprite("THBFA0","PLSFA0",PSP_FLASH);
		#### A 1 bright{
			HDFlashAlpha(64);
			A_Light2();
		}
		#### BA 1 bright;
		#### B 1 bright A_Light1();
		#### AB 1 bright;
		#### B 0 bright A_Light0();
		stop;
	RecoilLay:
		TNT1 A 0 {A_OverlayScale(PSP_WEAPON, 1, 1);A_OverlayRotate(PSP_WEAPON, 0);}
		TNT1 A 1
			{
				Vector2 Pivot = (FRandom(0, 1), FRandom(0, 1));
				A_OverlayPivot(PSP_WEAPON, Pivot.X, Pivot.Y);A_OverlayPivot(PSP_FLASH, Pivot.X, Pivot.Y);
				Float Ang = FRandom(-1, 1);
				A_OverlayScale(PSP_WEAPON, 1.02, 1.03);A_OverlayScale(PSP_FLASH, 1.02, 1.03);
				A_OverlayRotate(PSP_WEAPON, Ang);A_OverlayRotate(PSP_FLASH, Ang);
			}
		TNT1 A 2
			{
				A_OverlayScale(PSP_WEAPON, 1, 1, WOF_INTERPOLATE);A_OverlayScale(PSP_FLASH, 1, 1, WOF_INTERPOLATE);
				A_OverlayRotate(PSP_WEAPON, 0, WOF_INTERPOLATE);A_OverlayRotate(PSP_FLASH, 0, WOF_INTERPOLATE);
			}
		Stop;
		
	altfire:
	firemode:
		PLSR A 1 offset(1,2) A_WeaponBusy();
		#### B 2 offset(2,2);
		#### C 1 offset(1,3) A_StartSound("weapons/plasswitch",8);
		#### C 2 offset(0,4);
		#### C 3 offset(-1,5);
		#### C 4 offset(-1,6);
		#### B 3 offset(-1,5);
		#### B 2 offset(0,4){
			invoker.weaponstatus[0]^=TBF_ALT;
			A_SetHelpText();
		}
		#### A 1;
		PLSG A 1 offset(0,4);
		#### A 1 offset(1,3);
		goto nope;

	select0:
		PLSG A 0{
			invoker.weaponstatus[TBS_MAXRANGEDISPLAY]=int(
				(8000+200*invoker.weaponstatus[TBS_BATTERY])/HDCONST_ONEMETRE
			);
			A_CheckIdSprite("THBGA0","PLSGA0");
		}goto select0big;
	deselect0:
		PLSG A 0 A_CheckIdSprite("THBGA0","PLSGA0");
		#### A 0 A_Light0();
		goto deselect0big;

	unload:
		#### A 0{
			invoker.weaponstatus[0]|=TBF_JUSTUNLOAD;
			if(invoker.weaponstatus[TBS_BATTERY]>=0)
				return resolvestate("unmag");
			return resolvestate("nope");
		}goto magout;
	unmag:
		PLSR A 2 offset(0,0){
			A_SetCrosshair(21);
			A_MuzzleClimb(frandom(-1.2,-2.4),frandom(1.2,2.4));
		}
		#### B 3 offset(0,0);
		#### C 1 Offset(-10,-20);
		PLSR D 1 offset(36,60);
		PLSR D 1 offset(30,60);
		PLSR D 1 offset(25,50);
		PLSR D 1 offset(20,40);
		PLSR D 1 offset(16,30);
		PLSR D 1 offset(10,20);
		PLSR D 1 offset(6,10);
		PLSR D 0 offset(0,0);
		#### A 0{
			int bat=invoker.weaponstatus[TBS_BATTERY];
			A_MuzzleClimb(frandom(-1.2,-2.4),frandom(1.2,2.4));
			if(
				(
					bat<0
				)||(
					!PressingUnload()&&!PressingReload()
				)
			)return resolvestate("dropmag");
			return resolvestate("pocketmag");
		}

	dropmag:
		PLSR D 3 Offset(0,0) A_StartSound("weapons/plasopen",8);
		PLSR D 2 Offset(2,16);
		PLSR D 5 Offset(6,30){
			int bat=invoker.weaponstatus[TBS_BATTERY];
			invoker.weaponstatus[TBS_BATTERY]=-1;
			if(bat>=0){
				HDMagAmmo.SpawnMag(self,"HDBattery",bat);
			}}
		PLSR D 2 Offset(10,27) A_StartSound("weapons/plasload",8,CHANF_OVERLAP);
		PLSR D 2 Offset(5,23);
		PLSR D 1 Offset(1,16);
		PLSR D 1 Offset(0,0);
		goto magout;

	HandTakingBat:
		RVHA F 1 A_OverLayOffset(-26, -30, 55);
		RVHA F 1 A_OverLayOffset(-26, -36, 50, WOF_INTERPOLATE);
		RVHA F 1 A_OverLayOffset(-26, -44, 45, WOF_INTERPOLATE);
		RVHA F 1 A_OverLayOffset(-26, -56, 55, WOF_INTERPOLATE);
		RVHA F 1 A_OverLayOffset(-26, -64, 50, WOF_INTERPOLATE);
		RVHA F 1 A_OverLayOffset(-26, -75, 45, WOF_INTERPOLATE);
		RVHA G 2 A_OverLayOffset(-26, -80, 50);
		PLSR E 2 A_OverLayOffset(-26, -38, 30);
		PLSR E 2 A_OverLayOffset(-26, -30, 32, WOF_INTERPOLATE);
		PLSR E 1 A_OverLayOffset(-26, -23, 29, WOF_INTERPOLATE);
		PLSR E 2 A_OverLayOffset(-26, -15, 32, WOF_INTERPOLATE);
		PLSR E 2 A_OverLayOffset(-26, -4, 38, WOF_INTERPOLATE);
		PLSR E 2 A_OverLayOffset(-26, 4, 46, WOF_INTERPOLATE);
		PLSR E 2 A_OverLayOffset(-26, 11, 54, WOF_INTERPOLATE);
		PLSR E 2 A_OverLayOffset(-26, 18, 62, WOF_INTERPOLATE);
		Stop;
	pocketmag:
		---- A 0 A_OverLay(-26,"HandTakingBat");
		PLSR D 9;
		PLSR D 1 Offset(1,2) A_StartSound("weapons/plasopen",8);
		PLSR D 2 Offset(3,4);
		---- A 0{
			int bat=invoker.weaponstatus[TBS_BATTERY];
			invoker.weaponstatus[TBS_BATTERY]=-1;
			if(bat>=0){
				HDMagAmmo.GiveMag(self,"HDBattery",bat);
			}
		}
		PLSR D 1 Offset(5,5) A_StartSound("weapons/plasload",8);
		PLSR D 4 Offset(4,4);
		#### D 8 offset(1,1) A_StartSound("weapons/pocket",9);
		#### D 8 offset(0,0) A_StartSound("weapons/pocket",9,CHANF_OVERLAP);
		goto magout;

	magout:
		---- A 0 A_JumpIf(invoker.weaponstatus[0]&TBF_JUSTUNLOAD,"reload3");
		goto loadmag;

	reload:
		#### A 0{
			if(PressingZoom())SetWeaponState("CheckMag");
			else
			{
			invoker.weaponstatus[0]&=~TBF_JUSTUNLOAD;
			if(
				invoker.weaponstatus[TBS_BATTERY]<20
				&&countinv("HDBattery")
			)setweaponstate("unmag");
			}
		}goto nope;

	HandLoad:
		PLSR E 2 A_OverLayOffset(-26, 20, 62);
		PLSR E 2 A_OverLayOffset(-26, 14, 54, WOF_INTERPOLATE);
		PLSR E 2 A_OverLayOffset(-26, 9, 46, WOF_INTERPOLATE);
		PLSR E 2 A_OverLayOffset(-26, 1, 38, WOF_INTERPOLATE);
		PLSR E 2 A_OverLayOffset(-26, -10, 32, WOF_INTERPOLATE);
		PLSR E 2 A_OverLayOffset(-26, -20, 30, WOF_INTERPOLATE);
		PLSR E 2 A_OverLayOffset(-26, -31, 29, WOF_INTERPOLATE);
		PLSR E 2 A_OverLayOffset(-26, -34, 30, WOF_INTERPOLATE);
		PLSR E 2 A_OverLayOffset(-26, -42, 29, WOF_INTERPOLATE);
		RVHA G 2 A_OverLayOffset(-26, -70, 45);
		RVHA G 2 A_OverLayOffset(-26, -65, 50, WOF_INTERPOLATE);
		RVHA G 2 A_OverLayOffset(-26, -57, 57, WOF_INTERPOLATE);
		RVHA G 2 A_OverLayOffset(-26, -47, 64, WOF_INTERPOLATE);
		RVHA G 2 A_OverLayOffset(-26, -39, 70, WOF_INTERPOLATE);
		Stop;
	loadmag:
		PLSR D 2 offset(0,3){
			A_StartSound("weapons/pocket",9);
			if(health>39)A_SetTics(0);
		}
		#### DD 2 offset(0,2);
		#### D 2 offset(0,4) A_StartSound("weapons/pocket",9);
		#### A 0 A_OverLay(-26,"HandLoad");
		#### D 4 offset(0,3);
		#### D 6 offset(0,2);
		#### D 8 offset(0,3)A_StartSound("weapons/plasload",8);
		#### D 4 offset(0,4){if(health>39)A_SetTics(0);}
		#### D 4 offset(5,10)A_StartSound("weapons/plasclose",8);

		#### A 0{
			let mmm=HDMagAmmo(findinventory("HDBattery"));
			if(mmm)invoker.weaponstatus[TBS_BATTERY]=mmm.TakeMag(true);
		}goto reload3;

	reload3:
		PLSR D 1 offset(0,20){
			invoker.weaponstatus[TBS_MAXRANGEDISPLAY]=int(
				(8000+200*invoker.weaponstatus[TBS_BATTERY])/HDCONST_ONEMETRE
			);
			A_StartSound("weapons/plasclose2",8);
		}
		PLSR D 1 offset(10,30);
		PLSR D 1 offset(20,40);
		PLSR D 1 offset(28,50);
		PLSR D 1 offset(30,60);
		PLSR D 1 offset(36,70);
		#### C 2 Offset(-10,-20);
		#### C 1 Offset(-5,-10);
		#### B 2 offset(0,0);
		#### A 4 offset(0,0);
		goto nope;
	
	CheckMag:
		PLSR A 1 offset(1,2) A_WeaponBusy();
		#### B 2 offset(2,2);
		#### C 1 offset(1,3);// A_StartSound("weapons/plasswitch",8);
		#### C 1 offset(0,4);
		#### C 2 offset(-1,5);
	CheckMagLoop:
		#### C 3 offset(-1,6)A_JumpIf(!PressingReload(), 2);
		---- B 0 {
			if(invoker.weaponstatus[TBS_BATTERY]>0)A_Overlay(102, "Dumb");
			if(invoker.weaponstatus[0]&TBF_ALT)A_Overlay(103, "Dumb2");
		}
		Loop;
		#### B 2 offset(-1,5);
		#### B 1 offset(0,4);
		#### A 1;
		PLSG A 1 offset(0,4);
		#### A 1 offset(1,3);
		goto nope;
	
	Dumb:
		STUP O 5 {A_OverLayOffset(102,29,24);A_OverlayPivot(OverlayId(), 1, .5);Float Mag = invoker.weaponstatus[TBS_BATTERY];A_OverlayScale(OverlayId(), Mag/20, 1);}
		Stop;
	Dumb2:
		STUP X 5 A_OverLayOffset(OverlayId(),24,23);
		Stop;

	user3:
		#### A 0 A_MagManager("HDBattery");
		goto ready;

	spawn:
		PLAS A -1;
		stop;
	}
	override void initializewepstats(bool idfa){
		weaponstatus[TBS_BATTERY]=20;
	}
	
	override void loadoutconfigure(string input){
		if(Owner && Owner.FindInventory("ThunderBuster"))
		{
			Let inv = HDWeapon(Owner.FindInventory("ThunderBuster"));
			weaponstatus[TBS_BATTERY]=inv.weaponstatus[TBS_BATTERY];
			weaponstatus[TBS_WARMUP]=inv.weaponstatus[TBS_WARMUP];
			weaponstatus[TBS_HEAT]=inv.weaponstatus[TBS_HEAT];
			weaponstatus[TBS_MAXRANGEDISPLAY]=inv.weaponstatus[TBS_MAXRANGEDISPLAY];
			weaponstatus[0]=inv.WeaponStatus[0];
			inv.Destroy();
			Return;
		}
		
		int fm=getloadoutvar(input,"alt",1);
		if(!fm)weaponstatus[0]&=~TBF_ALT;
		else if(fm>0)weaponstatus[0]|=TBF_ALT;
	}
	
	Override Void Tick()
	{
		Super.Tick();
		if(Owner)Return;
		HDWeapon a = HDWeapon(Spawn("ThunderBuster", pos));
		if(a)
		{
			a.Angle = Angle;
			a.Pitch = Pitch;
			a.Vel = Vel;
			For(int i=0;i<HDWEP_STATUSSLOTS;i++)a.weaponstatus[i]=weaponstatus[i];
			Destroy();
		}
	}
}
enum NSHtbstatus{TBF_SAFETY=8,};